# 06_model_comparison.R
library(readr)
library(dplyr)

# Load metrics generated by 04_placement_prediction.R
if(file.exists("../results/tables/classification_metrics.csv")) {
  metrics <- read_csv("../results/tables/classification_metrics.csv", show_col_types = FALSE)
  
  cat("--- Model Comparison ---\n")
  print(metrics)
  
  # Save to model_comparison.csv as requested
  write_csv(metrics, "../results/tables/model_comparison.csv")
  cat("\nModel comparison table saved to results/tables/model_comparison.csv\n")
} else {
  cat("Error: classification_metrics.csv not found. Run 04_placement_prediction.R first.\n")
}
